### ISSUE TITLE
default python3 kernel uses python2

### ISSUE THREAD

**Issue by pretentious7** [sagemathinc/cocalc-docker#95] opened 2020-07-31 07:37 UTC
TO REPRODUCE:
docker run --restart=always --name=cocalc -d -v ~/cocalc:/projects -p 443:443 sagemathinc/cocalc       
start new notebook with python3 kernel then run

```
from platform import python_version
print(python_version())
```
should give python 2.7

**Comment by williamstein** [comment] 2020-07-31 14:29
I don't understand your question at all.   If you use the Python3 kernel, python_version() should be 3 and it is on cocalc-docker:

![image](https://user-images.githubusercontent.com/1276278/89044945-8babb180-d2ff-11ea-9ea1-c9b0cf8f7d9d.png)

Please clarify.

**Comment by pretentious7** [comment] 2020-07-31 16:42
Oh. I don't know then. but after restarting and starting the docker instance again it simply refuses to use the default python3 kernel

![Screenshot from 2020-07-31 12-36-05](https://user-images.githubusercontent.com/29604460/89057129-2077d480-d32b-11ea-8208-e00f783288c9.png)

I don't know what's going on exactly, I'm using the same docker command to start it.

**Comment by pretentious7** [comment] 2020-07-31 16:42
is this a configuration issue? if I just redownload the image and retain my projects folder will this still be a problem?

Thank you for your time.

**Comment by williamstein** [comment] 2020-07-31 17:02
> is this a configuration issue?

I don't know.

>  if I just redownload the image and retain my projects folder will this still be a problem?

Yes, since you ran cocalc-docker with `-v ~/cocalc:/projects`.  You should be able to confirm that your projects and other data are in the directory ~/cocalc on your computer.   Upgrading to the latest version is certainly a good idea.    See https://github.com/sagemathinc/cocalc-docker#upgrade

**Comment by pretentious7** [comment] 2020-08-01 05:30
so I did that and the issue still persists
![Screenshot from 2020-08-01 01-29-57](https://user-images.githubusercontent.com/29604460/89094863-9a917300-d396-11ea-8e19-4a3eddbefae5.png)

what could be causing this?

**Comment by pretentious7** [comment] 2020-08-01 05:31
> so I did that and the issue still persists
> ![Screenshot from 2020-08-01 01-29-57](https://user-images.githubusercontent.com/29604460/89094863-9a917300-d396-11ea-8e19-4a3eddbefae5.png)
> 
> what could be causing this?

note python3 kernel in top right and version 2.7 in the notebook

**Comment by williamstein** [comment] 2020-08-01 16:18
> what could be causing this?

I have absolutely no clue, and have never heard a report of this before.  

Please provide steps to start from scratch and reproduce the problem.  Above you wrote "TO REPRODUCE:" and provided steps, by thy do not reproduce the problem  for me.

Of course, I could as an admin mess with the kernel file at `/usr/share/jupyter/kernels/python3/kernel.json` to cause exactly the problem you see, or mess with /usr/bin/python3... but something silly like that isn't one of the steps you listed under "TO REPRODUCE".

**Comment by pretentious7** [comment] 2020-08-01 16:46
I'm not the only admin... so that might be the issue. Well I'll tell everyone to not mess around with anything they're not sure about.

How can I do a reset of the docker instance than? I supposed that using docker run should solve the problem, and that nothing in the projects directory would be able to mess with the jupyter kernel files... but apparently not.

**Comment by pretentious7** [comment] 2020-08-01 16:48
I'm also really rather confused because I've used cocalc in the exact same way before multiple times (great software) and I've never had this really weird thing happen. (I guessed it was an issue with the newest container that's why I wrote to reproduce)

**Comment by pretentious7** [comment] 2020-08-01 16:53
Even stranger, when I check `/usr/share/jupyter/kernels/python3/kernel.json` it shows `usr/bin/python3` and when I checked that (cd'd into /usr/bin then ./python3 --version , it says 3.6.9)

**Comment by williamstein** [comment] 2020-08-01 17:02
What about:
```
jupyter console --kernel=python3
```

**Comment by haraldschilly** [comment] 2020-08-01 17:15
* What's the output when you run `import platform; print(platform)` ? I expect a path to a file or package.
* What does `sys.version` say?

**Comment by pretentious7** [comment] 2020-08-01 18:47
>     * What's the output when you run `import platform; print(platform)` ? I expect a path to a file or package.
> 
>     * What does `sys.version` say?

sys.version: `'2.7.17` (default, Apr 15 2020, 17:20:14) \n[GCC 7.5.0]'`
`import platform; print(platform)` :  `<module 'platform' from '/usr/lib/python2.7/platform.pyc'>`

**Comment by pretentious7** [comment] 2020-08-01 18:49
> What about:
> 
> ```
> jupyter console --kernel=python3
> ```

did this in a cocalc terminal, got this error:
`~$ jupyter console --kernel=python3
Traceback (most recent call last):
  File "/usr/bin/jupyter-console", line 11, in <module>
    load_entry_point('jupyter-console==5.2.0', 'console_scripts', 'jupyter-console')()
  File "/projects/104d208d-bfa9-47a2-8fa7-38e8d222ec22/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/projects/104d208d-bfa9-47a2-8fa7-38e8d222ec22/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2861, in load_entry_point
    return ep.load()
  File "/projects/104d208d-bfa9-47a2-8fa7-38e8d222ec22/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2461, in load
    return self.resolve()
  File "/projects/104d208d-bfa9-47a2-8fa7-38e8d222ec22/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2467, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/jupyter_console/app.py", line 26, in <module>
    from jupyter_console.ptshell import ZMQTerminalInteractiveShell
  File "/usr/lib/python3/dist-packages/jupyter_console/ptshell.py", line 22, in <module>
    from IPython.utils.py3compat import cast_unicode_py2, input
ImportError: cannot import name 'cast_unicode_py2'`

**Comment by haraldschilly** [comment] 2020-08-01 19:50
Ok, well, thank you, but this just confirms python2. So weird... 

Couple other ideas:

1. Here, I see `~/.local/lib/python3.6/site-packages/pkg_resources/__init__.py` popping up. That's part of installing some python libs locally. You can do `rm -rf ~/.local/` to remove everything you did install locally. 

2. What about the actual jupyter kernels? 
    1. You can list them via `jupyter kernelspec list`
    2. Then you get names and paths. What will be interesting to know is for each kernel that is `python`, `python3`, etc. to know the content of the `kernel.json` file in the respective path. So, in particular, I wonder if there is a `python` or `python3` kernel in your home directory or globally, which is actually executing `/usr/bin/python`. The name of the kernel could claim to be "Python 3`, but `/usr/bin/python` is version 2.
    3. `python* -V` tells you what it really is, e.g.
```
$ /usr/bin/python -V
Python 2.7.17
$ /usr/bin/python3 -V
Python 3.6.9
$ /usr/bin/python2 -V
Python 2.7.17
```

**Comment by pretentious7** [comment] 2020-08-01 23:33
Ahhh that fixes it. so the python3 in the notebook was linked in the projects folder, so I changed that to python3 and now everything's OK, thank you!

**Closed** 2020-08-01 23:33 UTC
