### ISSUE TITLE
running jupyter notebook shows a REACT Warning.

### ISSUE THREAD

**Issue by arm2arm** [sagemathinc/cocalc-docker#84] opened 2020-05-15 09:04 UTC
I was testing the recent docker image, the jupyter notebook is throwing an error in the chrome console, but the notebook working w/o problem,( btw in the sage we dont have any warning or error)
![image](https://user-images.githubusercontent.com/2283443/82032416-74174200-969b-11ea-8869-6473e4cfa720.png)

thank you,
Arman

**Comment by williamstein** [comment] 2020-05-15 15:02
This is harmless. However, it suggests that we're building React in development rather than production mode, which is slower.  In production mode, all such checks and warnings should be surpressed.

(Of course eventually I want to fix the root cause of this warning -- it didn't exist when I wrote the relevant code, but newer versions of React added it.)  Again, this is a warning not an error.

**Comment by arm2arm** [comment] 2020-05-15 18:05
thank you for your explanation, maybe we can close it for the moment?

**Comment by williamstein** [comment] 2020-05-15 18:11
I'm fine with leaving it open.  I'm definitely concerned if we're building a debug version of react, since that would be slower, and we don't want that!

**Comment by williamstein** [comment] 2020-05-15 19:07
I checked and React is correctly built.  I don't know why you saw the above warning.  Closing for now, though if you can reproduce it let me know.

**Closed by williamstein** 2020-05-15 19:07 UTC
